// src/UseContexts/SeekerUseContext/JobRoleCategoriesContext.jsx
import React, { createContext, useState, useEffect } from "react";
import axios from "axios";
import { toast } from "react-toastify";

export const JobRoleCategoriesContext = createContext();

const API_URL = `${import.meta.env.VITE_API_BASE_URL}/api/job-role-categories`;

export const JobRoleCategoriesProvider = ({ children }) => {
  const [jobRoleCategories, setJobRoleCategories] = useState([]);
  const [loading, setLoading] = useState(true);

  // fetch
  const fetchJobRoleCategories = async () => {
    try {
      const res = await axios.get(API_URL);
      setJobRoleCategories(res.data.result || []);
    } catch (err) {
      console.error("Failed to fetch job role categories:", err);
      toast.error("Failed to load job role categories");
    } finally {
      setLoading(false);
    }
  };

  // add (admin only provides value; label is auto-generated by backend)
  const addJobRoleCategory = async (value) => {
    try {
      await axios.post(API_URL, { value });
      await fetchJobRoleCategories();
      toast.success("Job role category added successfully");
    } catch (err) {
      console.error("Failed to add job role category:", err);
      toast.error(err.response?.data?.message || "Failed to add job role category");
    }
  };

  // update
  const updateJobRoleCategory = async (id, value, is_active) => {
    try {
      await axios.put(`${API_URL}/${id}`, { value, is_active });
      await fetchJobRoleCategories();
      toast.success("Job role category updated successfully");
    } catch (err) {
      console.error("Failed to update job role category:", err);
      toast.error(err.response?.data?.message || "Failed to update job role category");
    }
  };

  // delete
  const deleteJobRoleCategory = async (id) => {
    try {
      await axios.delete(`${API_URL}/${id}`);
      setJobRoleCategories((prev) => prev.filter((c) => c.id !== id));
      toast.success("Job role category deleted successfully");
    } catch (err) {
      console.error("Failed to delete job role category:", err);
      toast.error("Failed to delete job role category");
    }
  };

  useEffect(() => {
    fetchJobRoleCategories();
  }, []);

  return (
    <JobRoleCategoriesContext.Provider
      value={{
        jobRoleCategories,
        loading,
        addJobRoleCategory,
        updateJobRoleCategory,
        deleteJobRoleCategory,
      }}
    >
      {children}
    </JobRoleCategoriesContext.Provider>
  );
};

export default JobRoleCategoriesProvider;
